healthcheck
MURATA-Laboratory/seminar-2022-backend pull request #3
Opened 2022-12-14 10:50 UTC by taito-nakada

新規で作成

2022-12-14 10:56 UTC, kathmandu777 requested changes
どのライブラリが使われているのかが不明なので、 `requirements.txt` を作成するか、`poetry` などの依存関係ツールを導入しよう！

2022-12-14 10:56 UTC, kathmandu777 commented on healthcheck.py
> +app=FastAPI()
PEPに従ったコーディングが出来ると良いね
```py
app = FastAPI()
```

formatter/linterを入れて、自動整形されるようにするとGOOD！

2022-12-14 10:56 UTC, kathmandu777 commented on healthcheck.py
> +async def root():
`root` -> `health` とかのほうが良いかな。
`get_health`, `health_check` などでも可。お好みで。`root`だと関数の内容の意味を表せてないかな〜。

2022-12-14 10:57 UTC, kathmandu777 commented
issueの紐付けGOOD！

2022-12-14 12:19 UTC, taito-nakada commented
修正した。
ライブラリが不明っていうのだけどうすればいいか分かってない。
`requirements.txt`はとりあえずpipでインストールするとこまでやってみた。

2022-12-14 17:15 UTC, kathmandu777 commented
@taito-nakada 
コードはLGTM

1. 「python 仮想環境」で検索して、ライブラリを仮想環境に入れるようにセットアップ
2. その仮想環境内で今回のPJが動くようにモジュールを入れる
3. `pip freeze > requirements.txt` みたいな感じでライブラリ情報を出力

目的としては、 @taito-nakada が動かしている環境と全く同じ環境を他の人が作れるようにすること。ライブラリがわからなかったり、バージョンが違うとコードが動かないからね。

2022-12-17 05:38 UTC, kathmandu777 requested changes
なんかパッケージ数多いと思うので、今度確認したいです。

2022-12-17 05:38 UTC, kathmandu777 commented on requirements.txt
> +PyGObject==3.36.0
ほんまか？

2022-12-17 05:41 UTC, taito-nakada commented on requirements.txt
> +PyGObject==3.36.0
余計なパッケージ入ってる？

2022-12-17 08:02 UTC, kathmandu777 commented on requirements.txt
> +PyGObject==3.36.0
多分そんな気がする

2022-12-17 09:42 UTC, taito-nakada commented on requirements.txt
> +PyGObject==3.36.0
なんか環境構築するためにいろんな方法試してたからそのせいかも

2022-12-27 13:17 UTC, kathmandu777 approved these changes
とりあえずLGTM
後々poetryとかのバージョン管理ツール使うように変更しよう！

2023-01-01 11:57 UTC, taito-nakada commented
poetryに変更を行った。

2023-01-06 11:50 UTC, kathmandu777 requested changes

2023-01-06 11:50 UTC, kathmandu777 commented on docker-compose.yml
> +    command: ["uvicorn", "healthcheck:resource", "--reload", "--host", "0.0.0.0"]
これ多分動かないね
頑張って修正してみて！

2023-01-21 07:06 UTC, kathmandu777 requested changes

2023-01-21 07:06 UTC, kathmandu777 commented on README.md
> +```rb
rb -> shかな？

2023-01-21 07:06 UTC, kathmandu777 commented on docker-compose.yml
> +    container_name: poetryc-compose
fastapiとかでいいかな

2023-01-21 07:06 UTC, merged